### ISSUE TITLE
GeoJSON-ex-NL-MulitpleSets(+800)

### ISSUE THREAD

**Issue by PalmJanssen** [INSPIRE-MIF/2017.2#13]
**GeoJSON example**

# Short description

Multiple Datasets on governmental platform. https://data.overheid.nl/data/dataset?q=geojson
Inspire theme: several but not according to data specifications.
https://data.overheid.nl/data/dataset?q=geojson

# Example instance
Over 800 GeoJSON and JSON encoded datasets

# Purpose & use

Use case: 

# Used simplification rules

# Additional information

**Comment by michellutz** [comment]
Are any of these data sets particularly relevant to our work, e.g. because they have national coverage or implement an INSPIRE data model?
