### ISSUE TITLE
ISO 19100 concepts

### ISSUE THREAD

**Issue by heidivanparys** [INSPIRE-MIF/2017.2#16]
**Glossary proposal**

# code
representation of a label according to a specified scheme
[ISO 19118:2011]

# conversion rule
rule for converting instances in the input data structure to instances in the output data structure
[ISO 19118:2011]

# data
reinterpretable representation of information in a formalized manner suitable for communication, interpretation, or processing
[ISO/IEC 2382-1:1993]

# encoding
conversion of data into a series of codes
[ISO 19118:2011]

# encoding rule
identifiable collection of conversion rules that define the encoding for a particular data structure
[ISO 19118:2011]

# information
knowledge concerning objects, such as facts, events, things, processes, or ideas, including concepts, that within a certain context has a particular meaning
[SOURCE: ISO/IEC 2382-1:1993]

# format
language construct that specifies the representation, in character form, of data objects in a record, file, message, storage device, or transmission channel
[ISO 19145:2013; ISO/IEC 2382‑15:1999]

**Comment by heidivanparys** [comment]
To be honest, I don't understand the definition of code, "representation of a label according to a specified scheme". Can this be explained?

**Comment by michellutz** [comment]
Thanks, Heidi. I used your proposal to create a [first version of the glossary](../blob/master/glossary.md).
