### ISSUE TITLE
ldproxy

### ISSUE THREAD

**Issue by cportele** [INSPIRE-MIF/2017.2#19]
**GeoJSON example**

# Short description
The [ldproxy](http://interactive-instruments.github.io/ldproxy/) tool can be used as a facade on existing WFS 2.0 services, including INSPIRE Download Services, to provide access to the data according to the [draft WFS 3.0 Core specification](https://cdn.rawgit.com/opengeospatial/WFS_FES/3.0.0-draft.1/docs/17-069.html). Supporting GeoJSON is one capability.

# Example instance
[Link to a feature of a square](https://www.ldproxy.nrw.de/rest/services/topographie/collections/ax_strassenverkehrsanlage/items/DENWAT01D000AAXE?f=json) (and the same feature in [GML](https://www.ldproxy.nrw.de/rest/services/topographie/collections/ax_strassenverkehrsanlage/items/DENWAT01D000AAXE?f=xml)). This is from a topographic dataset in North-Rhine Westphalia (Germany).

# Purpose & use
Support for users preferring JSON over XML.

# Used simplification rules
If ldproxy is used as a facade to a WFS 2.0 service, it transforms the GML 3.2 data automatically to GeoJSON. The mapping can be configured to some extent.

Properties that are not useful for a target audience can be ignored. In the example above, the `modellart` property is suppressed as each feature in the dataset has the same value (stating that it is large-scale topographic data).

The property names can be changed to something more meaningful to a non-expert, if needed. This wasn't necessary in the example above.

For properties with multiple values, these can be either flattened (using suffixes for the additional values to keep the property names unique) or be represented as an array. I do not think the topographic dataset used in the link above has attributes with multiple values, but if it has, the values are flattened.

For properties with complex values, these can be either represented as a JSON object or be flattened. In the example above, the data has been flattened (e.g. `lebenszeitintervall/AA_Lebenszeitintervall/beginnt`).

Values that are codes can be transformed to human readable labels. In the linked example above, this is only done in the [HTML representation](https://www.ldproxy.nrw.de/rest/services/topographie/collections/ax_strassenverkehrsanlage/items/DENWAT01D000AAXE?f=html) (the `art` property value of `4000` is translated to `Platz`), but this could also be applied in the GeoJSON output.  

# Additional information
Not all cases are covered yet in the current implementation. For example, `xlink:href` and `xsi:nil` attributes are ignored as a default.

**Comment by nmtoken** [comment]
Why not include links to other representations in the GML?

**Comment by cportele** [comment]
Because of XML Schema. Only elements that are explicitly foreseen can be added, i.e. additional links would the XML invalid. This would be different, if such links were included in the existing XML Schemas, but that is not the case. This is different in JSON Schema and how JSON is used.

What could be done is to include such links in "Link" headers in the response.

**Comment by nmtoken** [comment]
You could use CDATA, (at least to give hints), with no validation issues, and also xlink:href on the wfs:memebr to point to one alternate encoding.

**Comment by cportele** [comment]
* I don't see an existing XML element where such a CDATA block could be added in a useful way. For example, it does not belong into `gml:description`.
* Misusing `wfs:member` for this would violate the requirements. Each member is a separate feature that meets the selection criteria in the request.
* I think there will be continued use of XML/GML for a long time, but I also think that clients that are likely to make use of such capabilities will currently have a preference for JSON(-LD) - or HTML for immediate use in the browser.

**Comment by nmtoken** [comment]
I can't see how it violates the requirements (Each member is a separate feature that meets the selection criteria in the request.)  I mean why wouldn't the same rule apply to GeoJSON or HTML?  We're not saying the link is new feature in any case, just an alternative encoding of the same feature.

I'm just musing in any case, I just can't see why you wouldn't do it for interoperability, using the hypermedia approach rather than rely on HTTP or other protocols.

**Comment by cportele** [comment]
> I can't see how it violates the requirements (Each member is a separate feature that meets the selection criteria in the request.) 

If I select some set of features and it matches 9 features, then there have to be 9 `wfs:member` elements, each with one of the features (embedded or referenced). If I use `wfs:member` to add links to alternate representation then I will more than 9 `wfs:member` elements and those properties have a different semantics than `wfs:member`. 

> I mean why wouldn't the same rule apply to GeoJSON or HTML? 

The same rule applies there, too, but in those cases the "alternate encoding" links are not represented as members of the feature collection.
