### ISSUE TITLE
Should the simplification rules / GeoJSON encoding rule include profiling?

### ISSUE THREAD

**Issue by michellutz** [INSPIRE-MIF/2017.2#23]
Should the simplification rules / GeoJSON encoding rule include profiling, i.e. should they include the possibility to provide only a sub-sets of the properties (and maybe object types) defined in the INSPIRE conceptual data models?

**Comment by cportele** [comment]
I think it would be a mistake to disallow profiling. 

Take GeographicalName as an example. Only very few datasets will have all the rich information supported by the data type and for many use cases a simpler profile of the data type will be sufficient.

**Comment by MarieLambois** [comment]
Agree with Clemens, but then the status (official or not) of these profiles should be discussed.
