### ISSUE TITLE
Should we include simplification based on UML implementation models?

### ISSUE THREAD

**Issue by michellutz** [INSPIRE-MIF/2017.2#26]
Simplification rules could be implemented purely in the UML-to-encoding rules, or alternatively, in a first step, an implementation model could be manually developed in UML, and the UML-to-encoding rules could then be applied to that implementation model.

The latter was already foreseen in the data specifications template (for the UML-to-GML mapping):

![implementation_model](https://user-images.githubusercontent.com/5517424/46005258-25c3c280-c0b5-11e8-9ee5-88ca1cda2697.jpg)

**Comment by cportele** [comment]
Just a quick comment: The implementation model in UML does not have to be developed manually, it could also be derived in an automated way - this is basically what the ShapeChange Transformations (#22) do.

**Comment by PalmJanssen** [comment]
Good to hear this about ShapeChange. I still had the question open if the ShapeChange flattener produced a UML implementation model or an adapted (flattened) GML application schema. Of course it can also do the latter but I understand now that it also produces a UML. Perfect.

**Comment by cportele** [comment]
@PalmJanssen To be precise: ShapeChange internally uses a model specification that is based on a UML profile that covers all the information that we have seen and that supports the General Feature Model. When a model is transformed, the result is a new model in the same specification. Typically that derived model is processed to generate implementation artefacts, but you may also generate a EA file ([target: UML model](https://shapechange.net/targets/uml-model/)) or an XML file that can be used as input to ShapeChange later ([target: Model export](https://shapechange.net/targets/model-export/) - faster and avoid the 32-bit limitation that comes with EA).

**Comment by PalmJanssen** [comment]
@cportele Still perfect :)

**Comment by heidivanparys** [comment]
For the discussion, I would like to add this diagram (from the document mentioned in #28) that describes an approach, as also used by ShapeChange:

![billede](https://user-images.githubusercontent.com/11427611/46156680-8693fc00-c269-11e8-988d-74c07657652e.png)

So it is overall seen a two-step approach:

- simplify the UML model (e.g. on the fly, in memory)
- apply the UML-to-GML encoding rule

**Comment by MarieLambois** [comment]
I think that an intermediate UML model would be a ice way to document the simplification. If Shapechange can generate it, it is perfect !

**Comment by michellutz** [comment]
[2017.2 meeting 2018-09-28]
It was agreed that intermediate simplification steps at the UML model level should be included and might be useful to document the applied simplifications.
