### ISSUE TITLE
Should the GeoJSON encoding rule include simplification rules?

### ISSUE THREAD

**Issue by michellutz** [INSPIRE-MIF/2017.2#27]
Should the GeoJSON encoding rule focus on the spatial aspects or also include simplification rules for the non-spatial properties, e.g. to create flatter structures or pre-defined type mappings for certain types (e.g. geographical names)?

**Comment by tevbrasch** [comment]
I think this depends on what the objectives of the group are. Is our remit to only consider the essential technical changes needed to deliver the data model in an alternative encoding, or should we also be considering what the alternative encoding will eventually be used for?

**Comment by ghost** [comment]
I was thinking along the same lines and I am torn, showing first that we can translate the data model in an alternative encoding and then that it can also cover simplified versions would be the classic way to answer this, but a simpler structure will probably be prefered on the application side?

**Comment by michellutz** [comment]
[2017.2 meeting 2018-09-28]

- There could be separate GeoJSON encodings using complex or simple structures for the non-spatial properties.
- However, since the rationale for this action is to improve usability of INSPIRE data in standard GIS client applications, the GeoJSON encoding should use simple structures as much as possible.
