### ISSUE TITLE
Proposals for example data sets / themes / use cases

### ISSUE THREAD

**Issue by michellutz** [INSPIRE-MIF/2017.2#31]
Please use this issue to propose sample INSPIRE data sets, themes and/or use cases that we should consider in the action to develop examples of the proposed GeoJSON encoding and simplification rules. 

These examples should serve to prototype and test the proposed approaches, to focus our discussion and to illustrate the proposed approaches in the GP documents.

Where possible, please also include (pointers to) open sample data that can be re-used.

**Comment by michellutz** [comment]
[2017.2 meeting 2018-09-28]
The following themes were already proposed in the discussion: AD, O&M (AC-MF, OF and borehole-related observations), AU (to be checked with Spain), AM (to be checked with Denmark)

**Comment by heidivanparys** [comment]
👍 for AM

**Comment by nmtoken** [comment]
borehole ties in with GeoSciML, there is for example already a GeoSciML-Lite BoreholeView simplified structure.  http://onegeology.org/service_provision/data_preparation/lite.html or better http://geosciml.org/doc/geosciml-portrayal/2.0.1/documentation/html/

 There are already services providing this simplified view : http://resource.europe-geology.eu/service/wmsBorehole?service=WMS&request=GetCapabilities&
