### ISSUE TITLE
EarthResourceML-Lite (ERML-Lite)

### ISSUE THREAD

**Issue by nmtoken** [INSPIRE-MIF/2017.2#33]
**Simplified encoding example**

# Short description
Simplified schemas that takes the form of flat table of attributes (conformant to OGC Simple Features Level-0 profile); previously called EarthResourceML-Portrayal.  

ERML-Lite is an abridged version of the full EarthResourceML model and can be used to deliver simplified views on mineral occurrences and their commodities, mines, mining activities and mine waste products.

There are six EarthResourceML-Lite views descibed in the 2.0.1 standard, these are: MineView, CommodityResourceView, MineralOccurrenceView, MiningActivityView, MiningWasteView, and ProcessingPlantView

For full details of the ERML-Lite schema see: http://schemas.earthresourceml.org/earthresourceml-lite/2.0/erml-lite.xsd

For documention see: http://www.earthresourceml.org/earthresourceml-lite/2.0.1/documentation/

# Example instance

See the following URLs for example of service providing ERML-Lite output

http://13.95.69.121/geoserver/erl/ows?service=WMS&request=GetCapabilities&

http://13.95.69.121/geoserver/erl/ows?service=WFS&request=GetCapabilities&

**erl:CommodityResourceView**

    <?xml version="1.0" encoding="UTF-8"?>
    <erl:CommodityResourceView xmlns:erl="http://xmlns.earthresourceml.org/earthresourceml-lite/1.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink"
        xmlns:gml="http://www.opengis.net/gml"
        xsi:schemaLocation="http://xmlns.earthresourceml.org/earthresourceml-lite/1.0 
        http://schemas.earthresourceml.org/earthresourceml-lite/1.0/erml-lite.xsd"
        gml:id="ga.commodityResourceView.123456">
        <erl:identifier>http://data.geoscience.gov.au/feature/ga/commodityResourceView/ga.commodityResourceView.123456</erl:identifier>
        <erl:commodity>gold</erl:commodity>
        <erl:commodityRank>primary commodity</erl:commodityRank>
        <erl:commodityImportance>very large</erl:commodityImportance>
        <erl:mineralOccurrenceName>Lassiter's Reef</erl:mineralOccurrenceName>
        <erl:mineName>Lassiters</erl:mineName>
        <erl:totalEndowment>1300 Mt @ 2.7 g/t Au</erl:totalEndowment>
        <erl:totalReserves>800 Mt @ 2.9 g/t Au</erl:totalReserves>
        <erl:reservesCategory>proved ore reserves</erl:reservesCategory>
        <erl:totalResources>500 Mt @ 2.6 g/t Au</erl:totalResources>
        <erl:resourcesCategory>inferred mineral resource</erl:resourcesCategory>
        <erl:classificationMethodUsed>JORC code</erl:classificationMethodUsed>
        <erl:observationMethod>surveyed</erl:observationMethod>
        <erl:positionalAccuracy>0.5 metre</erl:positionalAccuracy>
        <erl:source>BHP Billiton Pty Ltd annual report, 2010</erl:source>
        <erl:commodityClassifier_uri>http://resource.geosciml.org/classifier/cgi/commodity-code/gold</erl:commodityClassifier_uri>
        <erl:mineralOccurrence_uri>http://data.geoscience.gov.au/feature/ga/mineralOccurrenceView/ga.mineralOccurrenceView.123456</erl:mineralOccurrence_uri>
        <erl:mine_uri>http://ga.gov.au/feature/mine/ga.mine.123456</erl:mine_uri>
        <erl:reservesCategory_uri>http://resource.geosciml.org/classifier/cgi/reserve-assessment-category/proved-ore-reserves</erl:reservesCategory_uri>
        <erl:resourcesCategory_uri>http://resource.geosciml.org/classifier/cgi/resource-assessment-category/inferred-mineral-resource</erl:resourcesCategory_uri>
        <erl:classificationMethodUsed_uri>http://resource.geosciml.org/classifier/cgi/classification-method-used/jorc-code</erl:classificationMethodUsed_uri>
        <erl:specification_uri>http://ga.gov.au/feature/commodityResource/ga.commodityResource.123456</erl:specification_uri>
        <erl:shape>
            <gml:Point srsName="epsg:4283" srsDimension="2"
                gml:id="GA.commodityResourceView.123456.point">
                <gml:pos>138.234 -26.747467</gml:pos>
            </gml:Point>
        </erl:shape>
    </erl:CommodityResourceView>

**erl:MineView**

    <?xml version="1.0" encoding="UTF-8"?>
    <erl:MineView xmlns:erl="http://xmlns.earthresourceml.org/earthresourceml-lite/1.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns:xlink="http://www.w3.org/1999/xlink"
        xmlns:gml="http://www.opengis.net/gml"
        xsi:schemaLocation="http://xmlns.earthresourceml.org/earthresourceml-lite/1.0 
        http://schemas.earthresourceml.org/earthresourceml-lite/1.0/erml-lite.xsd" gml:id="ga.mineView.123456">
        <erl:identifier>http://data.geoscience.gov.au/feature/ga/mineView/ga.mineView.123456</erl:identifier>
        <erl:name>Lassiters</erl:name>
        <erl:status>operating</erl:status>
        <erl:owner>BHP Billiton</erl:owner>
        <erl:startDate>1978-01-01</erl:startDate>
        <erl:endDate>2009-01-01</erl:endDate>
        <erl:observationMethod>surveyed</erl:observationMethod>
        <erl:positionalAccuracy>0.5 metres</erl:positionalAccuracy>
        <erl:source>BHP Billiton Pty Ltd annual report, 2010</erl:source>
        <erl:status_uri>http://resource.geosciml.org/classifier/cgi/mine-status/operating</erl:status_uri>
        <erl:specification_uri>http://data.geoscience.gov.au/feature/ga/mine/ga.mine.abc123</erl:specification_uri>
        <erl:shape xmlns:xlink="http://www.w3.org/1999/xlink" xlink:type="simple">
            <gml:Point srsName="epsg:4283" srsDimension="2" gml:id="GA.mineView.123456.point">
                <gml:pos>138.234 -26.747467</gml:pos>
            </gml:Point>
        </erl:shape>
    </erl:MineView>

**erl:MineralOccurrenceView**

    <?xml version="1.0" encoding="UTF-8"?>
    <erl:MineralOccurrenceView 
        xmlns:erl="http://xmlns.earthresourceml.org/earthresourceml-lite/1.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns:xlink="http://www.w3.org/1999/xlink"
        xmlns:gml="http://www.opengis.net/gml"
        xsi:schemaLocation="http://xmlns.earthresourceml.org/earthresourceml-lite/1.0 
        http://schemas.earthresourceml.org/earthresourceml-lite/1.0/erml-lite.xsd" gml:id="ga.mineralOccurrenceView.123456">
        <erl:identifier>http://data.geoscience.gov.au/feature/ga/mineralOccurrenceView/ga.mineralOccurrenceView.123456</erl:identifier>
        <erl:name>Lassiter's Reef</erl:name>
        <erl:mineralOccurrenceType>occurrence</erl:mineralOccurrenceType>
        <erl:commodity>gold, silver</erl:commodity>
        <erl:mineName>Lassiters</erl:mineName>
        <erl:geologicHistory>Mineralisation around 350-360 Ma</erl:geologicHistory>
        <erl:hostGeologicUnit>Killi Killi Formation</erl:hostGeologicUnit>
        <erl:mineralDepositModel>mesothermal vein gold</erl:mineralDepositModel>
        <erl:mineralOccurrenceShape>irregular</erl:mineralOccurrenceShape>
        <erl:explorationActivityType>subsurface exploration, detailed geophysics</erl:explorationActivityType>
        <erl:explorationActivityDuration>6 months</erl:explorationActivityDuration>
        <erl:explorationResult>mineral resource defined</erl:explorationResult>
        <erl:observationMethod>surveyed</erl:observationMethod>
        <erl:positionalAccuracy>0.5 metres</erl:positionalAccuracy>
        <erl:source>BHP Billiton Pty Ltd annual report, 2010</erl:source>
        <erl:mineralOccurrenceType_uri>http://resource.geosciml.org/classifier/cgi/mineral-occurrence-type/occurrence</erl:mineralOccurrenceType_uri>
        <erl:representativeCommodity_uri>http://resource.geosciml.org/classifier/cgi/commodity-code/precious-metal</erl:representativeCommodity_uri>
        <erl:mine_uri>http://data.geoscience.gov.au/feature/ga/mineView/ga.mineView.123456</erl:mine_uri>
        <erl:hostGeologicUnit_uri>http://dbforms.ga.gov.au/pls/www/geodx.strat_units.sch_full?wher=stratno=35397</erl:hostGeologicUnit_uri>
        <erl:mineralDepositModel_uri>http://resource.geoscience.gov.au/classifier/ga/mineral-deposit-model/mesothermal-vein-gold</erl:mineralDepositModel_uri>
        <erl:representativeAge_uri>http://resource.geosciml.org/classifier/ics/icschart/Carboniferous</erl:representativeAge_uri>
        <erl:representativeOlderAge_uri>http://resource.geosciml.org/classifier/ics/icschart/Famennian</erl:representativeOlderAge_uri>
        <erl:representativeYoungerAge_uri>http://resource.geosciml.org/classifier/ics/icschart/Tournaisian</erl:representativeYoungerAge_uri>
        <erl:specification_uri>http://ga.gov.au/feature/mineralOccurrence/ga.mineralOccurrence.123456</erl:specification_uri>
        <erl:shape>
            <gml:Point srsName="epsg:4283" srsDimension="2" gml:id="GA.mineralOccurrenceView.123456.point">
                <gml:pos>138.234 -26.747467</gml:pos>
            </gml:Point>
        </erl:shape>
    </erl:MineralOccurrenceView>

**erl:MiningActivityView**

    <?xml version="1.0" encoding="UTF-8"?>
    <erl:MiningActivityView 
        xmlns:erl="http://xmlns.earthresourceml.org/earthresourceml-lite/1.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns:xlink="http://www.w3.org/1999/xlink"
        xmlns:gml="http://www.opengis.net/gml"
        xsi:schemaLocation="http://xmlns.earthresourceml.org/earthresourceml-lite/1.0 
        http://schemas.earthresourceml.org/earthresourceml-lite/1.0/erml-lite.xsd" gml:id="ga.miningActivityView.123456">
        <erl:identifier>http://data.geoscience.gov.au/feature/ga/miningActivity/ga.miningActivityView.123456</erl:identifier>
        <erl:activityType>open-pit mining</erl:activityType>
        <erl:activityEndDate>2008-06-21</erl:activityEndDate>
        <erl:activityStartDate>2006-05-13</erl:activityStartDate>
        <erl:mineName>Lassiters</erl:mineName>
        <erl:commodity>gold</erl:commodity>
        <erl:operator>Smiths Mining Contractors Pty Ltd</erl:operator>
        <erl:oreProcessedAmount>7.1 Mt</erl:oreProcessedAmount>
        <erl:productionGrade>3.5 g/t Au</erl:productionGrade>
        <erl:producedMaterial>bullion</erl:producedMaterial>
        <erl:productionAmount>22.6 t</erl:productionAmount>
        <erl:productionRecovery>90.95%</erl:productionRecovery>
        <erl:observationMethod>surveyed</erl:observationMethod>
        <erl:positionalAccuracy>0.5 metres</erl:positionalAccuracy>
        <erl:source>BHP Billiton Pty Ltd annual report, 2010</erl:source>
        <erl:activityType_uri>http://resource.geosciml.org/classifier/cgi/mining-activity/open-pit-mining</erl:activityType_uri>
        <erl:mine_uri>http://data.geoscience.gov.au/feature/ga/mineView/ga.mineView.123456</erl:mine_uri>
        <erl:commodity_uri>http://resource.geosciml.org/classifier/cgi/commodity-code/gold</erl:commodity_uri>
        <erl:specification_uri>http://data.geoscience.gov.au/feature/ga/miningActivity/ga.miningActivity.abc123</erl:specification_uri>
        <erl:shape xmlns:xlink="http://www.w3.org/1999/xlink" xlink:type="simple">
            <gml:Point srsName="epsg:4283" srsDimension="2" gml:id="GA.miningActivityView.123456.point">
                <gml:pos>138.234 -26.747467</gml:pos>
            </gml:Point>
        </erl:shape>
    </erl:MiningActivityView>

**erl:MiningWasteView**

    <?xml version="1.0" encoding="UTF-8"?>
    <erl:MiningWasteView 
        xmlns:erl="http://xmlns.earthresourceml.org/earthresourceml-lite/1.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns:xlink="http://www.w3.org/1999/xlink"
        xmlns:gml="http://www.opengis.net/gml"
        xsi:schemaLocation="http://xmlns.earthresourceml.org/earthresourceml-lite/1.0 
        http://schemas.earthresourceml.org/earthresourceml-lite/1.0/erml-lite.xsd" gml:id="GA.miningWasteView.123456">
        <erl:identifier>http://data.geoscience.gov.au/feature/ga/miningWasteView/ga.miningWasteView.123456</erl:identifier>
        <erl:wasteType>acid water</erl:wasteType>
        <erl:storageType>surface</erl:storageType>
        <erl:mineName>Lassiters</erl:mineName>
        <erl:processingType>chemical treatment</erl:processingType>
        <erl:environmentalImpacts>liquid emission</erl:environmentalImpacts>
        <erl:materials>water</erl:materials>
        <erl:density>1 g/cc</erl:density>
        <erl:grade>0.04% CN</erl:grade>
        <erl:volume>53.7 megalitres</erl:volume>
        <erl:observationMethod>surveyed</erl:observationMethod>
        <erl:positionalAccuracy>0.5 metres</erl:positionalAccuracy>
        <erl:source>Department of Environment report XYA-01, 2011</erl:source>
        <erl:mine_uri>http://data.geoscience.gov.au/feature/ga/mineView/ga.mineView.123456</erl:mine_uri>
        <erl:wasteType_uri>http://myVocabulary/mining-waste-type/acid-water</erl:wasteType_uri>
        <erl:storageType_uri>http://resource.geosciml.org/classifier/cgi/waste-storage/surface</erl:storageType_uri>
        <erl:specification_uri>http://data.geoscience.gov.au/feature/ga/miningWaste/ga.miningWaste.abc123</erl:specification_uri>
        <erl:shape>
            <gml:Point srsName="epsg:4283" srsDimension="2" gml:id="GA.miningWasteView.123456.point">          
                <gml:pos>138.234 -26.747467</gml:pos>
            </gml:Point>
        </erl:shape>
    </erl:MiningWasteView>

**ProcessingPlantView**

    <?xml version="1.0" encoding="UTF-8"?>
    <erl:ProcessingPlantView 
        xmlns:erl="http://xmlns.earthresourceml.org/earthresourceml-lite/2.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns:xlink="http://www.w3.org/1999/xlink"
        xmlns:gml="http://www.opengis.net/gml/3.2"
        xsi:schemaLocation="http://xmlns.earthresourceml.org/earthresourceml-lite/2.0 http://schemas.earthresourceml.org/earthresourceml-lite/2.0/erml-lite.xsd"
        gml:id="test_v2.0.1">  
        <erl:identifier>http://data.geoscience.gov.au/feature/ga/processingPlantView/ga.processingPlantView.123456</erl:identifier>
        <erl:name>Lassiter's Mill</erl:name>
        <erl:processingPlantType>concentrator</erl:processingPlantType>
        <erl:startDate>1905-10-01</erl:startDate>
        <erl:endDate>2017-12-26</erl:endDate>
        <erl:status>abandoned</erl:status>
        <erl:commodity>gold, copper, silver</erl:commodity>
        <erl:inputMaterial>ore</erl:inputMaterial>
        <erl:product>gold-copper concentrate</erl:product> 
        <erl:observationMethod>surveyed</erl:observationMethod>
        <erl:positionalAccuracy>2 metres</erl:positionalAccuracy>
        <erl:source>BHP Billiton Pty Ltd annual report, 2010</erl:source>
        <erl:processingPlantType_uri>http://resource.geosciml.org/classifier/cgi/processing-plant-type/concentrator</erl:processingPlantType_uri>
        <erl:status_uri>http://resource.geosciml.org/classifier/cgi/mine-status/abandoned</erl:status_uri>
        <erl:representativeCommodity_uri>http://resource.geosciml.org/classifier/cgi/commodity-code/precious_metals</erl:representativeCommodity_uri>
        <erl:specification_uri>http://data.geoscience.gov.au/feature/ga/miningWaste/ga.processingPlant.123456</erl:specification_uri>
        <erl:shape>
            <gml:Point srsName="epsg:4283" srsDimension="2" gml:id="GAprocessingPlantView.123456.point">          
                <gml:pos>138.234 -26.747467</gml:pos>
            </gml:Point>
        </erl:shape>
    </erl:ProcessingPlantView>

# Underlying (INSPIRE) conceptual model
Simplifies the standard data model EarthResourceML for Mineral Resources

# Purpose & use
Developed for both WMS and simple feature WFS to more readily show Earth Resource data, using existing clients.

For WMS attributes follow defined element names to allow construction of harmonized styles, or the construction of SLD on-the-fly by aware clients.

For a discussion on harmonized styles for such a WMS see: https://themes.jrc.ec.europa.eu/discussion/view/119655/mapping-layers-to-be-provided-by-inspire-view-services-to-erml-lite

# Used simplification rules

Based on rules used in GeoSciML-Lite see: https://github.com/INSPIRE-MIF/2017.2/issues/34

# Additional information

**Comment by michellutz** [comment]
@nmtoken  Can this issue be closed (or moved)?

**Comment by nmtoken** [comment]
I guess can be closed if we're not looking into any more alternate encodings at the moment
