### ISSUE TITLE
Keeping the integrity of the INSPIRE ID and lifecycle info when proceeding to simplification

### ISSUE THREAD

**Issue by NathalieDelattre** [INSPIRE-MIF/2017.2#57]

**Comment by NathalieDelattre** [comment]
**adding the description**

simple features are also used for other process than viewing and spatial analysis , we could consider generalisation tools , and change detection tools allowing to register the historical changes of a same dataset. When simplifying by mean of alternative datamodel, we should ensure that UIds and life-cycle info are kepts. But from complex datamodel to simplify ones is that achievable?

**Comment by thorsten-reitz** [comment]
Doesn't this issue duplicate #60 to some degree?

**Comment by thorsten-reitz** [comment]
@NathalieDelattre would you agree to closing this issue?
