### ISSUE TITLE
keeping INS

### ISSUE THREAD

**Issue by NathalieDelattre** [INSPIRE-MIF/2017.2#58]
simple features are also used for other process than viewing and spatial analysis , we can integrate generalisation tools , and change detection tools allowing to register the historical changes of a same dataset. When simplifying by mean of alternative datamodel, we should ensure that UIds and life-cycle info are kepts. But from complex datamodel to simplify ones is that achievable?

**Comment by thorsten-reitz** [comment]
Duplicates #57
