### ISSUE TITLE
Issue with the description of the example simplifcation rule in the "Best practices for Model Transformations"

### ISSUE THREAD

**Issue by PeterParslow** [INSPIRE-MIF/2017.2#61]
This issue concerns the document at 2017.2/model-transformations/BestPracticesForModelTransformations.md, in particular, the description of the example, at [https://github.com/INSPIRE-MIF/2017.2/blob/master/model-transformations/BestPracticesForModelTransformations.md#rule-p1-rec001-flattening-of-complex-structures].

Here it says "If the upper bound of the resulting element multiplicity is not unbounded, but greater than 1", but in practice this rule is useful where the 'practical maximum multiplicity' is not large - i.e. the party intending to use the resulting model does not have any instances where the multiplicity is particularly large.

The example for the rule uses GN:NamedPlace, and in that application schema the maximum multiplicity is unbounded. It's just that in practice, there are rarely more than a few (four?) names. The same holds true for 'spelling', where the schema again has an unbounded multiplicity, but in practice there are few.

Suggest changing the description to "If the upper bound of the resulting element multiplicity is greater than one, and either not unbounded, or in practice not many instances occur, it is possible...."

Arguably, this is two different rules "flattening" and "reducing unbounded maximum multiplicity" - it may be simpler to understand if described as two rules.

**Comment by thorsten-reitz** [comment]
I have changed the structure of the document and adapted the rule as well. The new structures are on the draft branch.
