### ISSUE TITLE
EMF observation sample data

### ISSUE THREAD

**Issue by MarieLambois** [INSPIRE-MIF/2017.2#62]
BRGM has set up the following workflow with EMF data:
https://wfspoc.brgm-rec.fr/geoserver/ows?service=wfs&version=2.0.0&request=GetFeature&StoredQuery_ID=GetEnvironmentalMonitoringFacilityById&ID=Piezometre.06512X0037.STREMY.2
This is an ongoing work that will be continued in 2019 with new URIs, link to registers and links to OGC Sensor Things API. 

Those data could be used as sample data for the GeoJSON EMF encoding.

**Comment by thorsten-reitz** [comment]
@michellutz Not sure what I could do with this issue. I used the data from the service as input for the EFS examples.
