### ISSUE TITLE
Bijective/bijection (glossary)

### ISSUE THREAD

**Issue by heidivanparys** [INSPIRE-MIF/2017.2#69]
**Glossary proposal**

Add one or several proposals for terms and their definitions

# bijective model transformation
TODO

# bijective data transformation
TODO

# bijection
TODO
A reference to http://mathworld.wolfram.com/Bijection.html

**Comment by thorsten-reitz** [comment]
This is done as far as I can see. Can we close the issue?

**Comment by heidivanparys** [comment]
I have a few suggestions, see #83 .
