### ISSUE TITLE
Relations between important concepts in glossary?

### ISSUE THREAD

**Issue by heidivanparys** [INSPIRE-MIF/2017.2#75]
Could it be an idea to visualize the relations between important concepts in the glossary?

I did an attempt with the diagram below. The concepts not yet present in the glossary are explained below.

![Encoding according to ISO 19118](https://user-images.githubusercontent.com/11427611/54939196-3fd94300-4f28-11e9-9e7d-3a44390b7ea8.jpg)

**data element**
data instance
unit of data that is considered in context to be indivisible
[ISO/IEC 2382:2015, 2121599]

**data structure**
thing that is made of several data elements
NOTE This data structure concept is not the same as the following concept: data structure: physical or logical relationship among units of data and the data themselves [ISO/IEC 2382:2015, 2122353]

Editorial note for data structure: although mentioned many times in ISO 19118, data structure is actually not defined in that standard. The proposed definition is inspired by the second entry from https://www.oxfordlearnersdictionaries.com/definition/english/structure_1 : structure: a thing that is made of several parts.

**Comment by thorsten-reitz** [comment]
I am not entirely sure what we decided with respect to these terms and the image in the call. My notes say that it was not deemed necessary to include the image, but what about the two extra defintions? Should we include them for compelteness? They are currently not referenced from any of the geojson encoding rule docs.

**Comment by michellutz** [comment]
I would say, if the terms are not used, we don't need to include them in the glossary.

**Comment by heidivanparys** [comment]
As far as I remember, we concluded that the image should not be included.

The entries for data element and data structure were an attempt to clarify what is meant with "data structure" in the definitions of:

- conversion rule: rule for converting instances in the input **data structure** to instances in the output **data structure**
- encoding rule: identifiable collection of conversion rules that define the encoding for a particular **data structure**

Ideally, this should be been defined in ISO 19118, but that is not the case. Maybe the best we can do is give this input to ISO/TC 211, and not try to define in this action.

**Comment by thorsten-reitz** [comment]
@heidivanparys OK thanks for the clarification. Should we then close this issue here?

**Comment by heidivanparys** [comment]
Yes, let's close it.
