### ISSUE TITLE
SimpleCitation

### ISSUE THREAD

**Issue by heidivanparys** [INSPIRE-MIF/2017.2#79]
I am not convinced regarding the proposal for SimpleCitation. DocumentCitation and LegislationCitation were introduced as a simplification for CI_Citation. Most of the attributes are optional, so if only mandatory attributes are given, it is not a lot of data. So how much simpler would SimpleCitation be?

I also don't agree with the statement that 

> It can be combined with the Property Composition to Association rule to add more information from an external register.

as that proposal says that the document/legislation should be referred to by reference, so a simpler citation is not needed at all there.

Regarding

> This rule [...] removed finer grained information about dates

If the issue is that the use of CI_Date results in nested structures, which can be problematic for certain clients, how about applying a transformation as below? That solves the issues without removing finer grained information about the dates.

![Original model](https://user-images.githubusercontent.com/11427611/55157339-6d0e3700-515c-11e9-83c4-456c89c52e7f.jpg)

![Transformed model](https://user-images.githubusercontent.com/11427611/55157348-70092780-515c-11e9-8986-1a608a9756a6.jpg)

**Comment by thorsten-reitz** [comment]
@heidivanparys from my perspective we could also apply your proposed model. In `LegislationCitation`, would we also substitute the two `TM_Position` types?

**Comment by heidivanparys** [comment]
I have no idea why data type TM_Position was chosen at the time, and not Date. The definitions also use "date", so I am wondering if TM_Position isn't overkill for these attributes. Maybe someone knows the history of this? @michellutz ?

If a "date entered into force" and "date repealed" both are a date (and thus not a month or a year), then using Date instead of TM_Position for those attributes is sufficient and simpler. I would think that this is indeed the case for legal documents, but I'm far from an expert on legal matters...

![image](https://user-images.githubusercontent.com/11427611/58584723-38e7ed00-8257-11e9-806b-ad786e079d6b.png)

**Comment by michellutz** [comment]
No idea why both `Date` and `TM_Position` are used in these types. But I tend to agree that this should be harmonised (at least in the encoding).

For the simplification rule, the main idea behind `DocumentCitation` and `LegislationCitation` was indeed to simplify `CI_Citation` or, even better, not to use them at all, but rather point to an external register, where these documents are maintained (e.g. https://eur-lex.europa.eu/eli/dir/2007/2/oj for the INSPIRE Directive).

So maybe the rule should focus on simplifying `CI_Citation` and not so much on `DocumentCitation` and `LegislationCitation` .
