### ISSUE TITLE
Partial transformations?

### ISSUE THREAD

**Issue by heidivanparys** [INSPIRE-MIF/2017.2#84]
I looked at the documents again, and I was wondering, is it possible, that we are missing the concept of a partial transformation?

See https://en.wikipedia.org/wiki/Partial_function and http://mathworld.wolfram.com/PartialFunction.html . See the Simple Geographical Name for an example. If e.g. name status is omitted completely, then the process is not a (total) function at all, and as a consequence, it can of course not be a bijection either.

![image](https://user-images.githubusercontent.com/11427611/55753661-2f0dee80-5a4b-11e9-9b48-a850b6f614c9.png)

I don't want to make it more complicated than needed, but on the other hand, if we are using mathematical concepts, we should apply them correctly.

**Comment by thorsten-reitz** [comment]
@heidivanparys would you propose to add this as an entry to the glossary?

**Comment by heidivanparys** [comment]
This would have consequences in some of the model transformations.

> This rule discards individual metadata about geographical names, such as the name status and its nativeness. If this information is homogeneous, it should be documented in the dataset metadata. If it is heterogeneous, **this transformation will result in a loss of information and is not bijective**.

This is mathematically not correct: the transformation is not even a function. It is a partial function. And there it can, by definition, not be a bijection.

I would like to emphasize once more: I definitely don't want to make it more complicated than needed. But my suggestion would be to either drop the mathematical terms (perhaps "loss of information" is just fine?), or to apply the mathematical concepts correctly.

**Comment by michellutz** [comment]
Accept.
