### ISSUE TITLE
Logical Inconsistencies in EF Examples

### ISSUE THREAD

**Issue by KathiSchleidt** [INSPIRE-MIF/2017.2#88]
Unfortunately, various logical errors seem to have crept into the transformation process, leading to inconsistent data :(
Examples:

- Example1: Missing what is actually being measured (observedProperty); data is being provided from 2017, while the EF is listed as closed since 2014; Ground water level data is being provided with UoM "Degree Celsius" (a) wrong unit, should be m; b) UoM reference should if possible be to recognized vocabulary, i.e. unitsofmeasure.org)
- Example2: a bit better, but still measuring on a closed station, missing the backlink to the EF, EF Missing the name, all measurement metadata (observedProperty, procedure) missing from the example (but at least here the elements are foreseen)

I know these are details, but having these details consistent do help in understanding the content

**Comment by michellutz** [comment]
Accept. The examples should be updated.

**Comment by thorsten-reitz** [comment]
Weird, there was an inconsistency between the example in the text and the separte example file. Fixed these issues now.

I didn't have actual data for all empty fields. If you or Sylvain have domain knowledge on these measurements, feel free to make additions.

**Comment by thorsten-reitz** [comment]
With respect to the backlink, I followed the examples at OMSF-JSON:

https://raw.githubusercontent.com/opengeospatial/omsf-profile/master/omsf-json/examples/timeseries-observation_geojson_feature-collection.json

@ilkkarinne yet me know whether these exaples are correct, or whether I missed something.
