### ISSUE TITLE
Glossary item: Property name

### ISSUE THREAD

**Issue by jsaligoe** [INSPIRE-MIF/2017.2#90]
**Review Feedback**

## [Glossary for Alternative Encodings](https://github.com/INSPIRE-MIF/2017.2/blob/master/glossary.md)
Suggested item

## new item: Property name

Property name:  when expressed in a database, table, and/or GIS client, term is interchangeable with "field name", "feature object name", "attribute name", "field column name", etc.

**Comment by michellutz** [comment]
Accept
