### ISSUE TITLE
GeoJSON Encoding Rule - INSPIRE Addresses - Model Mapping

### ISSUE THREAD

**Issue by codinachssm** [INSPIRE-MIF/2017.2#91]
GeoJSON Encoding Rule - INSPIRE AD - Model mapping

There are minor errors on the Model Mapping document at https://github.com/INSPIRE-MIF/2017.2/blob/master/GeoJSON/ads/simple-addresses.md.
More concretely, at table where explains the mapping between the classes and properties of the original Addresses (AD) model to the Simplified Addresses (ADS) model):

![01-07-2019 10-58-23](https://user-images.githubusercontent.com/38311286/60438239-88338b80-9c10-11e9-9d2a-d5d39cf91386.png)

1. AD Name = ad:building ==> ADS Name = **endLifespanVersion**.

2. AD Name = ad:component (class = PostalDescriptor) ==> ADS Name = component.**ThoroughfareName**.

3. AD Name = ad:component (class = AddressAreaName) ==> ADS Name = component.**ThoroughfareName**.

**Comment by thorsten-reitz** [comment]
Thanks for spotting that one. A fix has been commited and merged.
