### ISSUE TITLE
GeoJSON Encoding Rule - INSPIRE Addresses - Model Mapping: designator/name

### ISSUE THREAD

**Issue by codinachssm** [INSPIRE-MIF/2017.2#92]
GeoJSON Encoding Rule - INSPIRE AD - Model mapping: **locator.designator.buildingIdentifier**

I’m following the model mapping described at https://github.com/INSPIRE-MIF/2017.2/blob/master/GeoJSON/ads/simple-addresses.md to convert from GML encoding Addresses to GeoJSON encoding Addresses. And I have the following question:

In the GML AD encoding we have 2 possible attributes (properties) to completely describe a building address:
1. locator{0}.AddressLocator.designator{0}.LocatorDesignator.designator
2. locator{0}.AddressLocator.name{0}.LocatorName.name{0}.GeographicalName.spelling{0}.SpellingOfName.text

But in GeoJSON encoding I can only find one way to define, describe or identify a building address: **locator.designator.buildingIdentifier**.
Is there any way to map my second property?

**Comment by thorsten-reitz** [comment]
You should be able to use `locator{0}.AddressLocator.name{0}.LocatorName.name{0}`. 

It seems we missed that property when creatign the mapping table, so I would add it now.
