### ISSUE TITLE
GeoJSON Encoding Rule - INSPIRE AD - Model mapping: locator.designator.addressNumber/addressExtension

### ISSUE THREAD

**Issue by codinachssm** [INSPIRE-MIF/2017.2#93]
GeoJSON Encoding Rule - INSPIRE AD - Model mapping: locator.designator.addressNumber/addressExtension

I’m following the model mapping described at https://github.com/INSPIRE-MIF/2017.2/blob/master/GeoJSON/ads/simple-addresses.md to convert from GML encoding Addresses to GeoJSON encoding Addresses. And I have the following question:

In our country ONE address can consist of 2 pairs of "addressNumber/addressExtension". For example: 
Number: 26, Extension: A
Number 28, Extension: null
Building name: "El Molí"

This address results in: "26A-28 El Molí".

In this case, the geoJSON resulting file should contain something similar to this (I know this is not correct but at conceptual level it should be similar to):

"locator.designator": {
	[ "addressNumber": "26",
	  "addressNumberExt": "A",
	  "addressNumber": "28"
	],
	"buildingIdentifier": "El Molí"
}

It is important to note that the pairs should be ordered, so it should be represented as an array.

Is there any way to implement this case under the GeoJSON model mapping for AD?

**Comment by thorsten-reitz** [comment]
The intent behind the GeoJSON encoding is to create a structure that, for most use cases, is fully flattened and does not use complex properties, as these have very limited support in a lot of client software.

For this reason, creating an object structure for the `locator.designator` property is not compliant to the encoding. Given that `locator.designator.addressNumber` is of type `String` in the `ads` model, you could just use the field for the full information:

`"locator.designator.addressNumber": "26A-28"`

**Comment by thorsten-reitz** [comment]
As there was no further comment, I will close this issue.
