### ISSUE TITLE
Availability/Access namespace "simple"

### ISSUE THREAD

**Issue by ftporthlnug** [INSPIRE-MIF/2017.2#96]
In the Model Transformation main document, 
(https://github.com/INSPIRE-MIF/2017.2/blob/master/modeltransformations/
TransformationRules.md),
a new namespace is mentioned:

Catalogue of simplifying Model Transformations
"These [less complex] types are added to a new simple namespace (http://inspire.ec.europa.eu/schemas/simple/1.0)."

I could not access this site.

When will it be available for use?

**Comment by thorsten-reitz** [comment]
@michellutz We could generate the schemas for ADS and EFS and place them there. However I considered this namespace to be a proposal that I believe we should breifly discuss. Should we also provide (XML) schemas in that namespace at all?

If not, I will clarify the statement cited in this issue.

**Comment by michellutz** [comment]
In my view the schemas should go into the https://inspire.ec.europa.eu/draft-schemas/ namespace and repository using their own specific path/folder (e.g. ads or efs). Once the good practice documents have been endorsed by the MIG, the schemas should then move into the https://inspire.ec.europa.eu/schemas/ namespace and repository.
